// Mapping of TheMealDB area (cuisine) names to flags and country codes
export const CUISINE_MAP = {
  American: { flag: '🇺🇸', code: 'US', name: 'United States' },
  British: { flag: '🇬🇧', code: 'GB', name: 'United Kingdom' },
  Canadian: { flag: '🇨🇦', code: 'CA', name: 'Canada' },
  Chinese: { flag: '🇨🇳', code: 'CN', name: 'China' },
  Croatian: { flag: '🇭🇷', code: 'HR', name: 'Croatia' },
  Dutch: { flag: '🇳🇱', code: 'NL', name: 'Netherlands' },
  Egyptian: { flag: '🇪🇬', code: 'EG', name: 'Egypt' },
  Filipino: { flag: '🇵🇭', code: 'PH', name: 'Philippines' },
  French: { flag: '🇫🇷', code: 'FR', name: 'France' },
  Greek: { flag: '🇬🇷', code: 'GR', name: 'Greece' },
  Indian: { flag: '🇮🇳', code: 'IN', name: 'India' },
  Irish: { flag: '🇮🇪', code: 'IE', name: 'Ireland' },
  Italian: { flag: '🇮🇹', code: 'IT', name: 'Italy' },
  Jamaican: { flag: '🇯🇲', code: 'JM', name: 'Jamaica' },
  Japanese: { flag: '🇯🇵', code: 'JP', name: 'Japan' },
  Kenyan: { flag: '🇰🇪', code: 'KE', name: 'Kenya' },
  Malaysian: { flag: '🇲🇾', code: 'MY', name: 'Malaysia' },
  Mexican: { flag: '🇲🇽', code: 'MX', name: 'Mexico' },
  Moroccan: { flag: '🇲🇦', code: 'MA', name: 'Morocco' },
  Polish: { flag: '🇵🇱', code: 'PL', name: 'Poland' },
  Portuguese: { flag: '🇵🇹', code: 'PT', name: 'Portugal' },
  Russian: { flag: '🇷🇺', code: 'RU', name: 'Russia' },
  Spanish: { flag: '🇪🇸', code: 'ES', name: 'Spain' },
  Thai: { flag: '🇹🇭', code: 'TH', name: 'Thailand' },
  Tunisian: { flag: '🇹🇳', code: 'TN', name: 'Tunisia' },
  Turkish: { flag: '🇹🇷', code: 'TR', name: 'Turkey' },
  Ukrainian: { flag: '🇺🇦', code: 'UA', name: 'Ukraine' },
  Vietnamese: { flag: '🇻🇳', code: 'VN', name: 'Vietnam' },
  Unknown: { flag: '🌐', code: 'UN', name: 'International' },
};

// Premium reviews for the Testimonials section
export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Elena Rostova',
    country: 'Italy 🇮🇹',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    review: 'Food Explorer Pro has completely transformed my weekly cooking. The global cuisine exploration is so interactive, it feels like traveling the world from my kitchen!',
  },
  {
    id: 2,
    name: 'Marcus Vance',
    country: 'United States 🇺🇸',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    review: 'The user interface is incredibly slick and premium. Finding instructions is lightning fast, and having the ingredients lists organized so dynamically makes shopping a breeze.',
  },
  {
    id: 3,
    name: 'Yuki Tanaka',
    country: 'Japan 🇯🇵',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    review: 'A chef\'s dream platform. The YouTube video embedding works flawlessly. I love being able to bookmark favorites for our weekend family culinary experiments.',
  },
  {
    id: 4,
    name: 'Amina Diop',
    country: 'France 🇫🇷',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop',
    rating: 4.8,
    review: 'Clean design, stunning visuals, and very responsive search. Discovering new dishes has never been this addictive. Highly recommended for recipe hunters!',
  },
];
