export const MOCK_CATEGORIES = [
  {
    idCategory: '1',
    strCategory: 'Chicken',
    strCategoryThumb: 'https://www.themealdb.com/images/category/chicken.png',
    strCategoryDescription: 'Chicken is a highly versatile meat.',
  },
  {
    idCategory: '2',
    strCategory: 'Beef',
    strCategoryThumb: 'https://www.themealdb.com/images/category/beef.png',
    strCategoryDescription: 'Beef is the culinary name for meat from cattle.',
  },
  {
    idCategory: '3',
    strCategory: 'Dessert',
    strCategoryThumb: 'https://www.themealdb.com/images/category/dessert.png',
    strCategoryDescription: 'Dessert is a course that concludes a meal.',
  },
  {
    idCategory: '4',
    strCategory: 'Pasta',
    strCategoryThumb: 'https://www.themealdb.com/images/category/pasta.png',
    strCategoryDescription: 'Pasta is a type of food typically made from an unleavened dough.',
  },
  {
    idCategory: '5',
    strCategory: 'Vegetarian',
    strCategoryThumb: 'https://www.themealdb.com/images/category/vegetarian.png',
    strCategoryDescription: 'Vegetarianism is the practice of abstaining from the consumption of meat.',
  },
  {
    idCategory: '6',
    strCategory: 'Seafood',
    strCategoryThumb: 'https://www.themealdb.com/images/category/seafood.png',
    strCategoryDescription: 'Seafood is any form of sea life regarded as food by humans.',
  },
];

export const MOCK_CUISINES = [
  { strArea: 'Italian' },
  { strArea: 'Mexican' },
  { strArea: 'Japanese' },
  { strArea: 'Indian' },
  { strArea: 'French' },
  { strArea: 'Spanish' },
  { strArea: 'American' },
  { strArea: 'British' },
];

export const MOCK_MEALS = [
  {
    idMeal: '52772',
    strMeal: 'Teriyaki Chicken Casserole',
    strMealThumb: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Chicken',
    strArea: 'Japanese',
  },
  {
    idMeal: '52940',
    strMeal: 'Chicken Handi',
    strMealThumb: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Chicken',
    strArea: 'Indian',
  },
  {
    idMeal: '52824',
    strMeal: 'Beef Wellington',
    strMealThumb: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Beef',
    strArea: 'British',
  },
  {
    idMeal: '52874',
    strMeal: 'Beef Bourguignon',
    strMealThumb: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Beef',
    strArea: 'French',
  },
  {
    idMeal: '52768',
    strMeal: 'Apple & Blackberry Crumble',
    strMealThumb: 'https://images.unsplash.com/photo-1519869325930-281384150729?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Dessert',
    strArea: 'British',
  },
  {
    idMeal: '52767',
    strMeal: 'Bakewell Tart',
    strMealThumb: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Dessert',
    strArea: 'British',
  },
  {
    idMeal: '53014',
    strMeal: 'Pizza Express Margherita',
    strMealThumb: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Pasta',
    strArea: 'Italian',
  },
  {
    idMeal: '52844',
    strMeal: 'Lasagne',
    strMealThumb: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Pasta',
    strArea: 'Italian',
  },
  {
    idMeal: '52959',
    strMeal: 'Classic Mexican Tacos',
    strMealThumb: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Beef',
    strArea: 'Mexican',
  },
  {
    idMeal: '52807',
    strMeal: 'Karahi Chicken',
    strMealThumb: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=600&auto=format&fit=crop',
    strCategory: 'Chicken',
    strArea: 'Indian',
  },
];

export const MOCK_MEAL_DETAILS = {
  '52772': {
    idMeal: '52772',
    strMeal: 'Teriyaki Chicken Casserole',
    strCategory: 'Chicken',
    strArea: 'Japanese',
    strMealThumb: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Preheat oven to 350 degrees F (175 degrees C).\r\n2. Stir together the chicken, soy sauce, garlic, ginger, and honey in a bowl.\r\n3. Mix with rice and fresh vegetables in a baking dish.\r\n4. Bake for 35 minutes until chicken is golden brown and cooked through.\r\n5. Drizzle extra teriyaki sauce and sprinkle sesame seeds before serving.',
    strYoutube: 'https://www.youtube.com/watch?v=DGGN7BvC9Sg',
    strIngredient1: 'Chicken',
    strIngredient2: 'Soy Sauce',
    strIngredient3: 'Ginger',
    strIngredient4: 'Garlic',
    strIngredient5: 'Honey',
    strIngredient6: 'Rice',
    strIngredient7: 'Sesame Seeds',
    strMeasure1: '500g',
    strMeasure2: '1/2 cup',
    strMeasure3: '1 tsp',
    strMeasure4: '2 cloves',
    strMeasure5: '2 tbsp',
    strMeasure6: '2 cups',
    strMeasure7: '1 tbsp',
  },
  '52940': {
    idMeal: '52940',
    strMeal: 'Chicken Handi',
    strCategory: 'Chicken',
    strArea: 'Indian',
    strMealThumb: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Heat oil in a pan and saute chopped onions and green chilies.\r\n2. Add ginger-garlic paste and chicken pieces. Cook until they turn white.\r\n3. Add yogurt, tomato paste, garam masala, turmeric, and chili powder.\r\n4. Simmer on low heat for 20 minutes until oil separates from the gravy.\r\n5. Garnish with fresh coriander leaves and cream.',
    strYoutube: 'https://www.youtube.com/watch?v=IO0iss3uzEw',
    strIngredient1: 'Chicken',
    strIngredient2: 'Onions',
    strIngredient3: 'Ginger Garlic Paste',
    strIngredient4: 'Yogurt',
    strIngredient5: 'Tomatoes',
    strIngredient6: 'Garam Masala',
    strIngredient7: 'Coriander',
    strMeasure1: '600g',
    strMeasure2: '2 large',
    strMeasure3: '1.5 tbsp',
    strMeasure4: '1/2 cup',
    strMeasure5: '3 medium',
    strMeasure6: '1 tsp',
    strMeasure7: 'To Garnish',
  },
  '52824': {
    idMeal: '52824',
    strMeal: 'Beef Wellington',
    strCategory: 'Beef',
    strArea: 'British',
    strMealThumb: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Sear the beef fillet on all sides in a hot pan until colored, then chill.\r\n2. Chop mushrooms finely and fry down to a dry paste (duxelles).\r\n3. Lay out cling film, drape with parma ham, spread with mushrooms, and wrap beef fillet inside. Chill for 15 minutes.\r\n4. Roll out puff pastry, brush borders with egg wash, place beef in center, wrap pastry around, and score patterns.\r\n5. Bake at 400F (200C) for 25-30 minutes until golden.',
    strYoutube: 'https://www.youtube.com/watch?v=5yB9_aJ6Lp8',
    strIngredient1: 'Beef Fillet',
    strIngredient2: 'Mushrooms',
    strIngredient3: 'Puff Pastry',
    strIngredient4: 'Parma Ham',
    strIngredient5: 'Egg Yolk',
    strIngredient6: 'English Mustard',
    strMeasure1: '800g',
    strMeasure2: '500g',
    strMeasure3: '500g',
    strMeasure4: '12 slices',
    strMeasure5: '2',
    strMeasure6: '2 tbsp',
  },
  '52874': {
    idMeal: '52874',
    strMeal: 'Beef Bourguignon',
    strCategory: 'Beef',
    strArea: 'French',
    strMealThumb: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Brown the beef cubes in olive oil with bacon lardons.\r\n2. Add carrots and sliced onions, then stir in garlic and tomato paste.\r\n3. Sprinkle with flour, toss, and cook for a few minutes.\r\n4. Pour in red wine and beef broth, add bouquet garni, cover, and simmer for 2.5 hours on low.\r\n5. Saute pearl onions and mushrooms separately, add to pot for final 15 minutes.',
    strYoutube: 'https://www.youtube.com/watch?v=q69H55_qB0Q',
    strIngredient1: 'Beef Cubes',
    strIngredient2: 'Bacon Lardons',
    strIngredient3: 'Red Wine',
    strIngredient4: 'Beef Broth',
    strIngredient5: 'Mushrooms',
    strIngredient6: 'Carrots',
    strIngredient7: 'Garlic',
    strMeasure1: '1kg',
    strMeasure2: '150g',
    strMeasure3: '3 cups',
    strMeasure4: '2 cups',
    strMeasure5: '250g',
    strMeasure6: '2 medium',
    strMeasure7: '4 cloves',
  },
  '52768': {
    idMeal: '52768',
    strMeal: 'Apple & Blackberry Crumble',
    strCategory: 'Dessert',
    strArea: 'British',
    strMealThumb: 'https://images.unsplash.com/photo-1519869325930-281384150729?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Toss peeled, sliced apples and blackberries with sugar and lemon juice. Place in baking dish.\r\n2. Combine flour, oats, butter, and brown sugar in a bowl. Rub with fingers to form breadcrumbs.\r\n3. Scatter the crumble mixture evenly over the fruit base.\r\n4. Bake at 375F (190C) for 40 minutes until fruit is bubbly and crumble topping is golden brown.\r\n5. Serve hot with custard or vanilla ice cream.',
    strYoutube: 'https://www.youtube.com/watch?v=48hZ2C0OcrA',
    strIngredient1: 'Apples',
    strIngredient2: 'Blackberries',
    strIngredient3: 'Flour',
    strIngredient4: 'Oats',
    strIngredient5: 'Butter',
    strIngredient6: 'Sugar',
    strMeasure1: '4 large',
    strMeasure2: '150g',
    strMeasure3: '1 cup',
    strMeasure4: '1/2 cup',
    strMeasure5: '100g',
    strMeasure6: '1/2 cup',
  },
  '52767': {
    idMeal: '52767',
    strMeal: 'Bakewell Tart',
    strCategory: 'Dessert',
    strArea: 'British',
    strMealThumb: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Line a tart tin with sweet shortcrust pastry and blind bake.\r\n2. Spread cherry or raspberry jam on the bottom of the pastry shell.\r\n3. Beat together butter, sugar, eggs, ground almonds, and almond extract (frangipane).\r\n4. Spoon frangipane over the jam, smooth the top, and sprinkle flaked almonds.\r\n5. Bake for 30-35 minutes until set. Dust with icing sugar.',
    strYoutube: 'https://www.youtube.com/watch?v=1ahpSTf_Pvk',
    strIngredient1: 'Pastry Case',
    strIngredient2: 'Raspberry Jam',
    strIngredient3: 'Butter',
    strIngredient4: 'Almonds Ground',
    strIngredient5: 'Eggs',
    strIngredient6: 'Almonds Flaked',
    strMeasure1: '1',
    strMeasure2: '3 tbsp',
    strMeasure3: '100g',
    strMeasure4: '100g',
    strMeasure5: '2',
    strMeasure6: '25g',
  },
  '53014': {
    idMeal: '53014',
    strMeal: 'Pizza Express Margherita',
    strCategory: 'Pasta',
    strArea: 'Italian',
    strMealThumb: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Roll out yeast dough on a floured surface to form a thin crust.\r\n2. Spread a thin layer of passata tomato sauce, leaving a border.\r\n3. Disperse fresh mozzarella cubes and fresh basil leaves evenly.\r\n4. Drizzle with extra virgin olive oil and season with salt and pepper.\r\n5. Bake at the highest possible oven setting (500F/260C) on a preheated pizza stone for 8-10 minutes.',
    strYoutube: 'https://www.youtube.com/watch?v=Mt5lgUZJVsc',
    strIngredient1: 'Pizza Dough',
    strIngredient2: 'Tomato Passata',
    strIngredient3: 'Mozzarella',
    strIngredient4: 'Basil Leaves',
    strIngredient5: 'Olive Oil',
    strMeasure1: '300g',
    strMeasure2: '1/2 cup',
    strMeasure3: '150g',
    strMeasure4: 'A handful',
    strMeasure5: '1 tbsp',
  },
  '52844': {
    idMeal: '52844',
    strMeal: 'Lasagne',
    strCategory: 'Pasta',
    strArea: 'Italian',
    strMealThumb: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Cook bolognese meat sauce with minced beef, onions, tomatoes, and red wine.\r\n2. Prepare a rich white bechamel sauce with butter, flour, and milk.\r\n3. Layer lasagna sheets, bolognese, and bechamel sauce in a baking dish.\r\n4. Top with grated parmesan and mozzarella cheese.\r\n5. Bake at 375F (190C) for 35 minutes until bubbling and golden on top.',
    strYoutube: 'https://www.youtube.com/watch?v=0wQ7PzKq5rE',
    strIngredient1: 'Lasagna Sheets',
    strIngredient2: 'Minced Beef',
    strIngredient3: 'Tomato Sauce',
    strIngredient4: 'Milk',
    strIngredient5: 'Cheese Mozzarella',
    strIngredient6: 'Parmesan',
    strMeasure1: '12 sheets',
    strMeasure2: '500g',
    strMeasure3: '400g',
    strMeasure4: '500ml',
    strMeasure5: '200g',
    strMeasure6: '50g',
  },
  '52959': {
    idMeal: '52959',
    strMeal: 'Classic Mexican Tacos',
    strCategory: 'Beef',
    strArea: 'Mexican',
    strMealThumb: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Heat corn tortillas on a dry skillet until soft and warm.\r\n2. Cook flank steak seasoned with cumin, garlic powder, and lime juice. Slice thinly.\r\n3. Top tortillas with steak slices, diced onions, and fresh cilantro.\r\n4. Serve with lime wedges and hot salsa dressing.',
    strYoutube: 'https://www.youtube.com/watch?v=Tnf1eB40NlI',
    strIngredient1: 'Tortillas',
    strIngredient2: 'Steak',
    strIngredient3: 'Onions',
    strIngredient4: 'Cilantro',
    strIngredient5: 'Limes',
    strMeasure1: '8 small',
    strMeasure2: '400g',
    strMeasure3: '1 small',
    strMeasure4: '1/2 cup',
    strMeasure5: '2',
  },
  '52807': {
    idMeal: '52807',
    strMeal: 'Karahi Chicken',
    strCategory: 'Chicken',
    strArea: 'Indian',
    strMealThumb: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop',
    strInstructions: '1. Heat oil in a wok (karahi) and brown the chicken pieces on high heat.\r\n2. Add crushed tomatoes, green chilies, ginger paste, and garlic paste.\r\n3. Season with salt, red pepper flakes, black pepper, and roasted cumin.\r\n4. Cover and cook on medium heat until tomatoes break down into a thick sauce.\r\n5. Garnish with thin julienne ginger strips and fresh coriander.',
    strYoutube: 'https://www.youtube.com/watch?v=eFscdK-aT4Y',
    strIngredient1: 'Chicken Pieces',
    strIngredient2: 'Tomatoes',
    strIngredient3: 'Green Chilies',
    strIngredient4: 'Ginger',
    strIngredient5: 'Garlic Paste',
    strMeasure1: '800g',
    strMeasure2: '4 large',
    strMeasure3: '4 pieces',
    strMeasure4: '2 tbsp',
    strMeasure5: '1 tbsp',
  },
};
